apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bill-vue.fullname" . }}-nginx-config
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  nginx.conf: {{ .Values.nginxConfig | nindent 6 }}