{{- /*
   Copyright VMware, Inc.
  SPDX-License-Identifier: APACHE-2.0
  */}}

  {{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "bill-vue.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "bill-vue.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "bill-vue.selectorLabels" . | nindent 6 }}
  ingress:
    # Allow inbound connections
    - ports:
        - port: {{ .Values.service.port }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ include "bill-vue.fullname" . }}-client: "true"
          {{- if .Values.networkPolicy.explicitNamespacesSelector }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress
          {{- end }}
      {{- end }}
{{- end }}
