apiVersion: v1
kind: Service
metadata:
  name: {{ include "bill-vue.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "bill-vue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bill-vue.selectorLabels" . | nindent 4 }}
