version: '1'

services:
  mysql:
    image: mysql:latest
    container_name: bill_mysql
    ports:
      - 3306:3306
    volumes:
      - container-volume:/var/lib/mysql
      - ./doc/demo.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bill
      MYSQL_USER: bill
      MYSQL_PASSWORD: password

volumes:
  container-volume: