apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.selfsignedCa.name }}
spec:
  isCA: true
  commonName: {{ .Values.selfsignedCa.commonName }}
  secretName: {{ .Values.selfsignedCa.secretName }}
  privateKey:
    algorithm: {{ .Values.selfsignedCa.privateKey.algorithm }}
    size: {{ .Values.selfsignedCa.privateKey.size }}
  issuerRef:
    name: {{ .Values.selfsignedIssuer.name }}
    kind: ClusterIssuer
    group: cert-manager.io